ritika728/Wellness_Wave

- css_files/faq.css
- html_files/bmi.html
- html_files/calorie.html
- html_files/faq.html
- html_files/fitnesstracking.html
- html_files/mental_health.html
- html_files/physical_health.html
- html_files/sleep.html
- html_files/spiritual_wellness.html
- index.html
- javascript/faq.js
Closes #23 
https://github.com/ritika728/Wellness_Wave/assets/114663382/1404e0f9-ed7c-4dae-ba94-f432f6a748cd
> Add: Faq page

- css_files/watintake.css
- html_files/fitnesstracking.html
- html_files/water_intake.html
- javascript/water_intake.js
> Fix Issue 33

- css_files/home.css
- css_files/workout.css
- html_files/faq.html
- html_files/fitnesstracking.html
- html_files/mental_health.html
- html_files/physical_health.html
- html_files/spiritual_wellness.html
- html_files/wellness.html
- html_files/workout.html
- index.html
- javascript/faq.js
- javascript/index.js
Mam, i have made the button in all possible pages.
> Go to top button added

- css_files/home.css
- html_files/Emotional_health.html
- html_files/Social_Well_Bieng.html
- html_files/bmi.html
- html_files/body_fat.html
- html_files/calorie.html
- html_files/faq.html
- html_files/fitnesstracking.html
- html_files/mental_health.html
- html_files/physical_health.html
- html_files/sleep.html
- html_files/spiritual_wellness.html
- html_files/water_intake.html
- html_files/wellness.html
- index.html
Closes #50 Update Details In Contact Section
Now users will be able to redirect to the links.
> Contact Section Working

- css_files/home.css
This pull request introduces a customized scrollbar to improve the overall user experience on the website. The scrollbar is designed to be smaller and smoother, providing a more aesthetically pleasing look. The changes are implemented in the `home.css` file.
**Closes:** #60 
**Working under JWoC'24**
> FIX: Update scrollbar 

- css_files/fitnesstracking.css
I have given enough space for the boxes, now no one would face issue in distortion in the size of boxes.
> Calculator box aligned

- html_files/fitnesstracking.html
> calorie calculator description added

- figma_file/figma.txt
Redesigned Home, Tracking, Wellness,FAQs,Terms and Condition page.
Fixes #59
> Added Figma Link

- css_files/sleep.css
- html_files/sleep.html
Issue No-#81
Close issue-#81 
Code Stack:
Under JWOC'24
> Styling of Sleep Calculator page

- css_files/home.css
- css_files/sleep.css
The footer is now fixed and is responsive for any screen size now.
Have a look @ritika728
> footer fixed fixes issue #114

- README.md
> Add a video of local installation in readme.md

- html_files/feedback.html
I have solved the footer issue. You can check it out.
> Footer updated in rateus page

- css_files/sleep.css
- html_files/bmi.html
- html_files/bmr.html
- html_files/body_fat.html
- html_files/calorie.html
- html_files/dri.html
- html_files/due_date.html
- html_files/heart_rate.html
- html_files/pace.html
- html_files/prot_intake.html
- html_files/sleep.html
- html_files/water_intake.html
> added reset button feature to all the calculators in tracking section

- css_files/home.css
- css_files/navbar.css
- enroll/index.html
- html_files/faq.html
- html_files/feedback.html
- html_files/fitnesstracking.html
- html_files/wellness.html
- index.html
fixed #139 
close #139 
Video 
https://github.com/ritika728/Wellness_Wave/assets/125949765/f8588bbf-6a5d-4c6d-a4dd-fda5b8e72275
> navbar style improved

- css_files/footer.css
- css_files/home.css
- enroll/index.html
- enroll/style.css
- html_files/faq.html
- html_files/feedback.html
- html_files/fitnesstracking.html
- html_files/wellness.html
- index.html
Title : improvement in footer #140
issue #140 
close #140 
https://github.com/ritika728/Wellness_Wave/assets/125949765/59f9fcab-b349-4331-b030-36f49d959b63
> improvement in footer #140

- html_files/bac.html
- html_files/bloodpressure.html
- html_files/bmi.html
- html_files/bmr.html
- html_files/body_fat.html
- html_files/breastcancer.html
- html_files/calorie.html
- html_files/dri.html
- html_files/due_date.html
- html_files/heart_rate.html
- html_files/ideal_weight.html
- html_files/leanmass.html
- html_files/pace.html
- html_files/prot_intake.html
- html_files/sleep.html
- html_files/water_intake.html
> [BUG] Absence of navbar in all calculator #161

- html_files/fitnesstracking.html
Added Animations To Tracking Page
Issue No = #142 .
> Added Animations To Tracking Page

- css_files/calc.css
- html_files/calc.html
- html_files/fitnesstracking.html
- javascript/calc.js
Please check and close issue #159 
Thank you
> FEATURE: Add calories burnt calculator #159

- css_files/bmi.css
- css_files/body_fat.css
- css_files/prot.css
> editted the css of tracking section calculators

- css_files/hambg.css
- css_files/navbar.css
- enroll/index.html
- html_files/bac.html
- html_files/blog.html
- html_files/bloodpressure.html
- html_files/bmi.html
- html_files/bmr.html
- html_files/body_fat.html
- html_files/breastcancer.html
- html_files/calc.html
- html_files/calorie.html
- html_files/dri.html
- html_files/due_date.html
- html_files/faq.html
- html_files/feedback.html
- html_files/fitnesstracking.html
- html_files/heart_rate.html
- html_files/ideal_weight.html
- html_files/leanmass.html
- html_files/pace.html
- html_files/prot_intake.html
- html_files/sleep.html
- html_files/water_intake.html
- html_files/wellness.html
- index.html
- javascript/hambg.js
Improved the Hamburger as it was not properly working. Added a new Hamburger in each and every webpage which works perfectly fine and is completely responsive !!
Issue = #167
> Improved the Hamburger

- css_files/home.css
- enroll/index.html
- html_files/blog.html
- html_files/faq.html
- html_files/feedback.html
- html_files/fitnesstracking.html
- html_files/wellness.html
- index.html
- javascript/hambg.js
- javascript/index.js
Customized Scrollbar to all the pages !!
Issue No = #175
> Customized Scrollbar

- html_files/fitnesstracking.html
Tite : [BUG] Tracking Page Inconsistency
Issue : #177 
Screenshots :
> Fixed UI of Tracking Page

- css_files/faq.css
- css_files/feedback.css
- css_files/mode.css
- enroll/index.html
- enroll/style.css
- html_files/blog.html
- html_files/faq.html
- html_files/feedback.html
- html_files/fitnesstracking.html
- html_files/wellness.html
- index.html
> Add a light and dark mode button . #74

- html_files/Emotional_health.html
- html_files/Social_Well_Bieng.html
- html_files/depression.html
- html_files/diet.html
- html_files/lifeexpectancy.html
- html_files/mental_health.html
- html_files/physical_health.html
- html_files/spiritual_wellness.html
- index.html
Title : Replace all old Navbar & Improve UI 
issue : #186
changes : Replaced old Navbar to new one at following pages...
- Depression Schenning Risk Calculator
- Life Expectancy Calculator
-  Physical health page
- Mental health page
- Emotional health page
- Social Wellbeing page
- Spiritual wellbeing page
- Nutrition page 
Example Screenshots :
> Replace all old Navbar & Improve UI
